(define (problem blocksworld-problem)
  (:domain blocksworld)
  (:objects a b c - block)
  (:init (handempty) (on a b) (on b c) (ontable c) (clear a))
  (:goal (and (clear a) (clear b) (clear c) (ontable a) (ontable b) (ontable c)))
)