(define (problem blocksworld-problem)
  (:domain blocksworld)
  (:objects a b c d e f g h - block)
  (:init (handempty) (ontable a) (ontable b) (ontable c) (ontable d)
         (ontable e) (ontable f) (ontable g) (ontable h)
         (clear a) (clear b) (clear c) (clear d)
         (clear e) (clear f) (clear g) (clear h))
  (:goal (and (handempty) (ontable a) (ontable b) (ontable c) (ontable d)
              (ontable e) (ontable f) (ontable g) (ontable h)
              (clear a) (clear b) (clear c) (clear d)
              (clear e) (clear f) (clear g) (clear h)))
)